allOf:
  - $ref: https://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/collection.yaml
  - type: object
    properties:
      links:
        type: array
        items:
          $ref: bblocks://ogc.ogc-utils.json-link